# Camera intrinsic matrix parameters (OpenCV)
camera:
  fx: 544.771755
  fy: 546.966312
  cx: 322.376103
  cy: 245.357925

  width: 640
  height: 480

semantic_pcl:
  color_image_topic: "/camera/rgb/image_raw"
  #depth_image_topic: "/camera/depth_registered/image_raw"
  depth_image_topic: "/camera/depth/image_raw"
  point_type: 1
  frame_id: "camera_link"
  dataset: "ade20k" # sunrgbd
  #dataset: "sunrgbd" # sunrgbd
  model_path: "/home/tataha/Downloads/semantic_trained_model/pspnet_50_ade20k.pth"
  #model_path: "/home/interns/xuan/models/pspnet_sunrgbd_best_model180625_5k.pth"
